name: healthful
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  custom_clippers: ^2.0.0
  image_picker: ^1.0.7
  autocomplete_textfield: ^2.0.1
  http: ^1.2.1
  firebase_core: ^2.27.1
  google_sign_in: ^6.1.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  flutter_spinkit: ^5.2.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/

